theme: jekyll-theme-minimal
title: Machine Cinema Poland - Daily AI Newsletter
description: Codzienny przegląd najnowszych wiadomości AI ze świata
markdown: kramdown
include: ["assets"]
plugins:
  - jekyll-feed

# Minimal theme customization
minimal:
  show_downloads: false
  search: false
  social_links: false

# Exclude unnecessary files
 exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - CNAME
