name: Daily newsletter build

on:
  schedule:
    - cron: "0 7 * * *"
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_PORT: ${{ secrets.SMTP_PORT }}
  SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  NEWSLETTER_FROM: ${{ secrets.NEWSLETTER_FROM }}
  NEWSLETTER_TO: ${{ secrets.NEWSLETTER_TO }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ github.ref_name != '' && github.ref_name || github.event.repository.default_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate newsletter
        run: python generate_all.py --mode live --verbose

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily newsletter update"
          branch: ${{ env.TARGET_BRANCH }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send newsletter email
        if: env.SMTP_HOST != '' && env.NEWSLETTER_TO != ''
        run: python send_email.py --html site/index.html --subject "Machine Cinema AI Newsletter"
